import { themeQuartz } from 'ag-grid-community';
import { colors, typography, borderRadius } from './designSystem';

export const agGridThemeLight = themeQuartz.withParams({
  accentColor: colors.primary.main,
  backgroundColor: colors.light.bg.primary,
  foregroundColor: colors.light.text.primary,
  chromeBackgroundColor: colors.light.bg.secondary,
  headerTextColor: colors.light.text.primary,
  oddRowBackgroundColor: colors.light.bg.primary,
  borderColor: colors.light.border.subtle,
  rowHoverColor: colors.light.interactive.hover,
  selectedRowBackgroundColor: colors.light.interactive.selected,
  rangeSelectionBorderColor: colors.primary.main,
  columnBorder: true,
  headerColumnBorder: true,
  fontFamily: typography.fontFamily.sans,
  fontSize: 12,
  headerFontSize: 12,
  headerFontWeight: 600,
  rowHeight: 28,
  headerHeight: 32,
  spacing: 3,
  cellHorizontalPadding: 8,
  rowGroupIndentSize: 20,
  wrapperBorderRadius: borderRadius.md,
  borderRadius: borderRadius.md,
  iconSize: 14,
  checkboxCheckedBackgroundColor: colors.primary.main,
  cardShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
});

export const agGridThemeDark = themeQuartz.withParams({
  accentColor: colors.primary.light,
  backgroundColor: colors.dark.bg.primary,
  foregroundColor: colors.dark.text.primary,
  chromeBackgroundColor: colors.dark.bg.secondary,
  headerTextColor: colors.dark.text.primary,
  oddRowBackgroundColor: colors.dark.bg.primary,
  borderColor: colors.dark.border.subtle,
  rowHoverColor: colors.dark.interactive.hover,
  selectedRowBackgroundColor: colors.dark.interactive.selected,
  rangeSelectionBorderColor: colors.primary.light,
  columnBorder: true,
  headerColumnBorder: true,
  fontFamily: typography.fontFamily.sans,
  fontSize: 12,
  headerFontSize: 12,
  headerFontWeight: 600,
  rowHeight: 28,
  headerHeight: 32,
  spacing: 3,
  cellHorizontalPadding: 8,
  rowGroupIndentSize: 20,
  wrapperBorderRadius: borderRadius.md,
  borderRadius: borderRadius.md,
  iconSize: 14,
  checkboxCheckedBackgroundColor: colors.primary.light,
  cardShadow: '0 2px 4px 0 rgba(0, 0, 0, 0.3)',
});
